CREATE DATABASE IF NOT EXISTS videoteca;
USE videoteca;

CREATE TABLE IF NOT EXISTS Registi (
ID_Regista INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR (30) NOT NULL,
Cognome VARCHAR (30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Generi
ID_Genere INT AUTO_INCREMENT PRIMARY REY,
Nome VARCHAR (30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Film(
ID_Film INT AUTO_INCREMENT PRIMARY KEY,
Titolo VARCHAR (100) NOT NULL,
Anno_Uscita YEAR NOT NULL,
Durata INT NOT NULL,
ID_Regista INT NOT NULL,
ID_Genere INT NOT NULL,
FOREIGN KEY (ID_Regista) REFERENCES Registi (ID_Regista) ON DELETE NO ACTION ON UPDATE CASCADE,
FOREIGN KEY (ID_Genere) REFERENCES Generi (ID_Genere) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Clienti(
ID_Cliente  INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR (30) NOT NULL,
Cognome VARCHAR (30) NOT NULL,
Email VARCHAR (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Ricevute(
ID_Ricevuta INT AUTO_INCREMENT PRIMARY KEY,
Data_Scandenza DATE NOT NULL,
ID_Cliente INT NOT NULL,
ID_Film INT NOT NULL.
FOREIGN KEY (ID_Cliente) REFERENCES Clienti (ID_Cliente) ON DELETE NO
ACTION ON UPDATE CASCADE,
FOREIGN KEY (ID_Film) REFERENCES Film (ID_Film) ON DELETE NO
ACTION ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Stati_Pagamenti(
ID_Stato INT AUTO_INCREMENT PRIMARY KEY,
Descrizione VARCHAR (30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Pagamenti(
ID_Pagamento INT AUTO_INCREMENT PRIMARY KEY,
Data_Pagamento DATE NOT NULL,
Prezzo INT NOT NULL,
ID_Ricevuta INT NOT NULL,
Stato_Pagamento INT NOT NULL,
REFERENCES (ID_Ricevuta) REFERENCES (ID_Ricevuta) ON DELETE NO
ACTION ON UPDATE CASCADE,
FOREIGN KEY (Stato_Pagamento) REFERENCES Stato_Pagamenti (ID_Stato) ON DELETE NO
ACTION ON UPDATE CASCADE
);
